language: swift
os: osx
xcode_project: ./dev.xcodeproj
xcode_scheme: dev
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone X

script:
- xcodebuild analyze -project ./dev/dev.xcodeproj -scheme dev -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project ./dev/dev.xcodeproj -scheme dev -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=NO
- xcodebuild build -project ./dev/dev.xcodeproj -scheme dev ONLY_ACTIVE_ARCH=NO
- xcodebuild archive -scheme dev -archivePath ./dev/Archives/dev.xcarchive ONLY_ACTIVE_ARCH=NO
- xcodebuild -exportPath ./Releases/ -archivePath ./dev/Archives/dev.xcarchive -exportOptionsPlist ./dev/Archives/ExportOptions.plist ONLY_ACTIVE_ARCH=NO
