language: swift
os: osx
xcode_project: ./dev/dev.xcodeproj
xcode_scheme: dev
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPhone X
osx_image: xcode10.1

script:
- xcodebuild analyze -project ./dev/dev.xcodeproj -scheme dev -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project ./dev/dev.xcodeproj -scheme dev -destination 'platform=iOS Simulator,name=iPhone X' ONLY_ACTIVE_ARCH=NO
- xcodebuild build -project ./dev/dev.xcodeproj -allowProvisioningUpdates -scheme dev ONLY_ACTIVE_ARCH=NO
- xcodebuild archive -scheme dev -archivePath ./dev/Archives/dev.xcarchive -allowProvisioningUpdates ONLY_ACTIVE_ARCH=NO
- xcodebuild -exportArchive -exportPath ./Releases/ -allowProvisioningUpdates -archivePath ./dev/Archives/dev.xcarchive -exportOptionsPlist ./dev/Archives/ExportOptions.plist ONLY_ACTIVE_ARCH=NO
